title: Jeon
email: jeonnoej@naver.com
author:
  picture: http://site.hugocarreira.me/assets/img/compressed/hugo.jpg #URL FORMAT
  name: J
  location: Seoul - Corea
  description: "JS"
description: Web and JS
baseurl: "/"
url: https://jeonnoej.github.io/
twitter_username: jeonnoej
github_username:  jeonnoej
github_url: https://www.github.com/jeonnoej

# Build settings
permalink: :title
paginate: 1
paginate_path: "page:num"
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
